//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebaCodere
{
    using System;
    using System.Collections.Generic;
    
    public partial class Empleados
    {
        public int Codigo { get; set; }
        public string Nombre { get; set; }
        public string Puesto { get; set; }
        public Nullable<int> Sueldo { get; set; }
        public string Superior { get; set; }
        public int Grupo { get; set; }
    
        public virtual Grupo Grupo1 { get; set; }
    }
}
